[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_nft_marketplace = "HnEci36EQ4njjc1DK7XjEyykubLVXEzSux3KR1ga31wB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
